### ISSUE TITLE
edge浏览器，股票涨跌幅提醒，股票名是undefined

### ISSUE THREAD

**Issue by WenjiZeng** [bu6030/stock-and-fund-chrome#2]
edge浏览器，股票涨跌幅提醒，股票名是undefined

**Comment by bu6030** [comment]
能否再详细点？是提醒的通知？还是哪个？例如我下面这个？
![image](https://github.com/bu6030/stock-and-fund-chrome/assets/11482988/f40520e4-8030-4c5e-9673-d214d177c8fe)
我在2.0.1的分支中修改了基金分时图的名称undefined的问题，不知道你说的是不是这个问题
![image](https://github.com/bu6030/stock-and-fund-chrome/assets/11482988/04a864b9-f3aa-4f10-992f-abaa3c06fc9e)
基金点击进入不再显示undefined
