### ISSUE TITLE
基金的当日净值什么时候更新？

### ISSUE THREAD

**Issue by wqinzheng** [bu6030/stock-and-fund-chrome#3]
晚上9点多的时候，插件上基金的当时净值还是估算值

**Comment by bu6030** [comment]
仍然是估算值，当日净值需要到历史净值页面去看。
<img width="814" alt="image" src="https://github.com/bu6030/stock-and-fund-chrome/assets/11482988/63d4da10-91c0-4484-ad51-e83a9ad504b5">
<img width="828" alt="image" src="https://github.com/bu6030/stock-and-fund-chrome/assets/11482988/bcf9b09b-859c-41b5-a8ba-22888f0357ec">

**Comment by wqinzheng** [comment]
那当日的收益率，收益情况咋更新，还是估算的啊

**Comment by bu6030** [comment]
> 那当日的收益率，收益情况咋更新，还是估算的啊

是的，我的插件基金是估算的，不完全准确。但是股票是准确的。
不过刚才看了下9点后更新的净值计算，通过这个公式（当日的净值-前一天的净值）*持仓数，竟然和我支付宝的的当日盈利完全一致，看来可以研究研究如何更加准确的计算了。

（当日的净值-前一天的净值）*持仓数就是当日的盈利。

2.0.5分支修改完了，晚上九点以后净值更新后，打开插件查看，页面显示的数据就是更新完毕的真实盈利，不再是估值了。

**Comment by bu6030** [comment]
我已经修改完毕，大约晚上九点更新净值后，会根据（当日新出的净值-前一天的净值）*持仓数来计算基金收益，已经和我的支付宝计算结果完全一致。
